## Load data

In [1]:
import pandas as pd
df = pd.read_csv('data.csv')
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [2]:
df['Maker_Model']= df['Make']+ " " + df['Model']

In [3]:
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP,Maker_Model
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,BMW 1 Series M
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,BMW 1 Series
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,BMW 1 Series
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,BMW 1 Series
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500,BMW 1 Series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120,Acura ZDX
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670,Acura ZDX
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620,Acura ZDX
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920,Acura ZDX
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995,Lincoln Zephyr

In [4]:
# Select features from original dataset to form a new dataframe
df1 = df[['Engine Fuel Type','Transmission Type','Driven_Wheels','Market Category','Vehicle Size', 'Vehicle Style', 'Maker_Model']]
df1.head()

,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style,Maker_Model
0,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,BMW 1 Series M
1,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible,BMW 1 Series
2,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe,BMW 1 Series
3,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe,BMW 1 Series
4,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible,BMW 1 Series

In [5]:
# For each row, combine all the columns into one column
df2 = df1.apply(lambda x: ','.join(x.astype(str)), axis=1)
df2.head()

0    premium unleaded (required),MANUAL,rear wheel ...
1    premium unleaded (required),MANUAL,rear wheel ...
2    premium unleaded (required),MANUAL,rear wheel ...
3    premium unleaded (required),MANUAL,rear wheel ...
4    premium unleaded (required),MANUAL,rear wheel ...
dtype: object

In [6]:
df2.shape

(11914,)

In [7]:
# Store them in a pandas dataframe
df_clean = pd.DataFrame({'clean': df2})
df_clean.head()

                                               clean
0  premium unleaded (required),MANUAL,rear wheel ...
1  premium unleaded (required),MANUAL,rear wheel ...
2  premium unleaded (required),MANUAL,rear wheel ...
3  premium unleaded (required),MANUAL,rear wheel ...
4  premium unleaded (required),MANUAL,rear wheel ...

In [8]:
# Create the list of list format of the custom corpus for gensim modeling
sent = [row.split(',') for row in df_clean['clean']]
# show the example of list of list format of the custom corpus for gensim modeling
sent[:2]

[['premium unleaded (required)',
  'MANUAL',
  'rear wheel drive',
  'Factory Tuner',
  'Luxury',
  'High-Performance',
  'Compact',
  'Coupe',
  'BMW 1 Series M'],
 ['premium unleaded (required)',
  'MANUAL',
  'rear wheel drive',
  'Luxury',
  'Performance',
  'Compact',
  'Convertible',
  'BMW 1 Series']]

## Train Word2Vec model (skip-gram)

In [9]:
%pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /opt/conda/lib/python3.11/site-packages (from gensim) (1.26.4)
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Requirement already satisfied: smart-open>=1.8.1 in /opt/conda/lib/python3.11/site-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /opt/conda/lib/python3.11/site-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 8.5 MB/s eta 0:00:00a 0:00:01
Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 10.5 MB/s eta 0:00:0000:0100:01
Installing collected packages: scipy, gensim
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.2
    Uninstalling scipy-1.16.2:
      Successfully uninstalled scipy-1.16.2
Successfully installed gensim-4.3.3 scipy-1.13.1
Note: you may need to restart the kernel to use updated packages.

In [10]:
# from gensim import models
import numpy as np
from gensim.models import Word2Vec
model = Word2Vec(sent, min_count=1,vector_size= 300,workers=5, window=10, sg = 1, epochs=100)
# model = Word2Vec(sent, min_count=1,size= 300,workers=5, window=10, sg = 1, iter=100)

**vector_size**: The number of dimensions of the embeddings and the default is 100.

**window**: The maximum distance between a target word and words around the target word. The default window is 5.

**min_count**: The minimum count of words to consider when training the model; words with occurrence less than this count will be ignored. The default for min_count is 5.

**workers**: The number of partitions during training and the default workers is 3.

**sg**: The training algorithm, either CBOW(0) or skip gram(1). The default training algorithm is CBOW.

In [11]:
model.wv['Toyota Camry']

array([ 1.26503021e-01,  1.99135188e-02,  2.12237108e-02, -1.12264656e-01,
        5.78070506e-02, -1.02675170e-01,  8.76522511e-02,  5.08118719e-02,
       -5.81556447e-02,  1.23678945e-01,  5.22919148e-02, -5.96431158e-02,
        2.04617560e-01,  2.21867874e-01,  1.01264874e-02,  1.33223878e-02,
        1.46352783e-01,  2.90466119e-02, -1.75555810e-01,  4.04997729e-02,
       -1.26015693e-01, -7.37275034e-02, -1.44719318e-01,  1.63658410e-01,
       -1.33172020e-01, -1.01887889e-01, -2.60039806e-01,  8.59565064e-02,
       -1.32235989e-01, -1.97947621e-01,  3.64351124e-01,  1.05879448e-01,
       -2.19378009e-01, -7.12289801e-03,  5.39995730e-02, -5.66923656e-02,
        1.48036778e-01, -1.22724921e-01, -6.22406639e-02,  4.32070792e-02,
       -1.97881609e-01, -2.90343650e-02,  1.81851506e-01,  2.18475625e-01,
       -2.92992014e-02,  7.86800683e-02, -6.99224398e-02, -1.08043365e-02,
        2.93151408e-01,  9.83382165e-02,  2.10223362e-01, -2.73309290e-01,
        1.03803918e-01, -5.60089983e-02, -1.70125738e-01, -7.77655188e-03,
        7.42968696e-04,  1.18240165e-02, -9.89831835e-02,  3.06976009e-02,
        9.71364528e-02,  1.17485814e-01,  1.30607679e-01,  3.40802372e-01,
       -2.47075692e-01,  9.39193815e-02,  1.49997128e-02,  8.74950811e-02,
       -8.51641968e-02,  2.60251433e-01,  1.69177338e-01,  5.94542176e-02,
        2.73258448e-01, -9.45095941e-02,  1.16091587e-01,  6.17727265e-02,
       -3.46489251e-02,  1.47683606e-01, -1.16763644e-01,  2.96399900e-04,
        1.07739046e-01, -9.07637700e-02,  1.81399360e-02,  2.63294220e-01,
        1.03825361e-01,  5.14356829e-02,  3.18022579e-01, -5.08567914e-02,
        1.87632442e-02, -8.40943679e-02,  1.50829792e-01,  8.88490528e-02,
       -3.01380128e-01, -5.78420386e-02, -3.76050062e-02, -3.86071876e-02,
        1.88057750e-01, -1.28534198e-01,  2.83906180e-02, -3.35450843e-02,
        2.24591449e-01,  9.05489475e-02,  7.24044666e-02,  6.75360262e-02,
        7.13206902e-02,  1.15480229e-01,  2.75656074e-01, -1.29761994e-01,
       -2.64224678e-01, -6.86861435e-03, -1.34138018e-01,  2.44709432e-01,
       -1.54929668e-01,  1.03921399e-01, -4.56102341e-02,  4.95783128e-02,
        3.45340490e-01, -5.20051084e-02, -6.49547204e-02, -2.29007825e-01,
        1.17278583e-02,  2.32567877e-01,  1.81291953e-01, -9.08693448e-02,
        1.85342029e-01,  4.20148849e-01, -3.76938254e-01, -1.56436637e-01,
       -8.31918046e-02,  3.08094114e-01,  8.15135688e-02, -9.86582413e-02,
       -1.42058888e-02, -4.76529837e-01,  8.99811015e-02,  4.33077723e-01,
       -5.52908704e-02,  2.15972997e-02, -4.69478726e-01, -2.51456559e-01,
        3.03719789e-02, -2.65968926e-02, -7.07037672e-02,  1.55894607e-01,
        8.96758661e-02, -4.99191321e-02, -7.74830729e-02, -6.48536757e-02,
        9.37429890e-02, -2.20393717e-01,  1.54113829e-01, -2.72341013e-01,
       -8.45783576e-02, -1.46234512e-01, -1.42909825e-01, -8.42424948e-03,
       -1.51355267e-01,  2.77036607e-01, -1.62064031e-01,  3.87637198e-01,
        1.10590048e-01, -2.26830140e-01, -5.13103493e-02,  3.31375122e-01,
        5.19297421e-01, -4.01611142e-02, -1.82362944e-01, -1.13881044e-01,
       -7.85736367e-02,  1.32869065e-01, -4.11939681e-01, -9.31537375e-02,
        1.73256546e-01,  3.88932526e-02,  1.19914345e-01, -6.75700754e-02,
       -2.83064693e-01,  9.91267562e-02,  2.76768923e-01, -5.12084775e-02,
        5.90138622e-02,  1.22871257e-01, -2.97099560e-01, -2.95517176e-01,
       -2.67596155e-01, -1.60907283e-01,  3.76759082e-01,  2.60848731e-01,
        2.32627854e-01, -3.89749438e-01,  2.47185707e-01,  3.24788511e-01,
       -2.25182220e-01, -1.07971877e-01, -8.92466530e-02, -4.93183732e-01,
       -1.25427023e-01,  1.88034028e-01, -7.06100687e-02, -1.06906787e-01,
       -1.37310579e-01,  1.67701155e-01, -2.74762511e-01, -1.75469562e-01,
        4.64860111e-01,  2.56446362e-01,  2.33629957e-01,  2.23187074e-01,
       -1.66633483e-02,  1.69485077e-01, -1.27242297e-01, -3.57128680e-01,
        3.15415978e-01, -1.57568142e-01,  1.79917023e-01, -1.36585861e-01,
       -1.84094489e-01, -6.35712504e-01, -4.13325459e-01, -5.03234804e-01,
        2.40473822e-01, -1.83229521e-01,  1.04768693e-01, -2.45160684e-01,
       -1.29410222e-01,  2.15112995e-02,  1.13617152e-01, -2.67083235e-02,
        3.29027139e-02, -1.97341666e-01,  1.48404941e-01, -2.89408118e-01,
        7.75345936e-02,  6.18147589e-02, -1.71235502e-01, -1.85125712e-02,
        3.26387882e-01,  2.18171641e-01,  1.87550977e-01, -5.06862625e-02,
        1.38789132e-01,  8.58447999e-02,  1.68689892e-01,  2.45228156e-01,
        1.42792324e-02, -1.30459234e-01, -1.18842266e-01, -1.92617953e-01,
        6.77486435e-02, -7.29880035e-02,  3.34528714e-01, -2.82754928e-01,
        3.22700441e-01,  1.87611043e-01, -1.84963673e-01, -1.94455072e-01,
        2.09738746e-01,  1.84475616e-01, -5.02554923e-02, -1.08949408e-01,
        3.12756896e-02, -2.04560190e-01,  4.22415644e-01,  4.23308760e-02,
       -1.78141221e-01,  7.36988410e-02,  1.74791887e-01,  2.08612561e-01,
       -1.44574225e-01,  9.62737277e-02, -1.11921571e-01,  9.34228450e-02,
       -2.78147552e-02,  4.00296636e-02, -2.03190506e-01, -6.97086528e-02,
       -4.67385612e-02,  2.62924880e-01, -2.88029790e-01, -8.66203830e-02,
       -9.92855057e-02,  1.33687168e-01,  4.68749553e-02,  1.04660660e-01,
        1.83556885e-01,  1.26991838e-01, -2.00241685e-01, -1.03110317e-02,
       -5.13004921e-02,  4.37414795e-02, -2.16221921e-02,  1.06864929e-01,
        8.88886303e-02,  7.49905705e-02,  4.15192336e-01,  8.31463486e-02,
        2.91653514e-01, -2.78170686e-02,  1.09266415e-01, -2.45441124e-01],
      dtype=float32)

In [12]:
model.wv.similarity('Porsche 718 Cayman', 'Nissan Van')

0.5602686

In [13]:
model.wv.similarity('Porsche 718 Cayman', 'Mercedes-Benz SLK-Class')

0.82772154

In [14]:
model.wv.most_similar('Mercedes-Benz SLK-Class')[:5]

[('Mercedes-Benz SL-Class', 0.976067841053009),
 ('Cadillac XLR-V', 0.9739692807197571),
 ('Mercedes-Benz SLC-Class', 0.947677731513977),
 ('Porsche Boxster', 0.9305784702301025),
 ('BMW M', 0.9219624996185303)]

In [15]:
model

In [16]:
import numpy as np
def cosine_distance (model, word,target_list , num) :
    cosine_dict ={}
    word_list = []
    a = model.wv[word]
    for item in target_list :
        if item != word :
            b = model.wv[item]
            cos_sim = np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))
            cosine_dict[item] = cos_sim
    dist_sort=sorted(cosine_dict.items(), key=lambda dist: dist[1],reverse = True) ## in Descending order
    for item in dist_sort:
        word_list.append((item[0], item[1]))
    return word_list[0:num]

In [17]:
# only get the unique Maker_Model
Maker_Model = list(df.Maker_Model.unique())

# Show the most similar Mercedes-Benz SLK-Class by cosine distance
cosine_distance(model,'Mercedes-Benz SLK-Class',Maker_Model,5)

[('Mercedes-Benz SL-Class', 0.97606796),
 ('Cadillac XLR-V', 0.97396946),
 ('Mercedes-Benz SLC-Class', 0.9476778),
 ('Porsche Boxster', 0.9305786),
 ('BMW M', 0.9219625)]

# Activity

1. Use the customer complaint data to estimate the word embedding vectors
2. Find similar words to 'debt', 'collection', 'risk'